### ISSUE TITLE
Discuss architecture

### ISSUE THREAD

**Issue by stanislavkaliuk** [Render-Devs/SimpleEngine#2]
We need to discuss architecture and way of  development.
How we will design our engine? Will it be dedicated .dll (.lib) and will be used in separate project or we will put everyhing in one executable project?
Will we try to use moduled and autoconnected subsystems (dedicated render, ui)?

**Comment by BatReg** [comment]
I think .dll (.lib) that the user can use in a separate project is the preferable approach.
Also, we can try to use subsystems as modules, so we will be sure the physics subsystem, for example, will not depend on the rendering subsystem in any way.
